/* Generated By:JavaCC: Do not edit this line. GALParserConstants.java */
package org.zhjh.galaxykit.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface GALParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int IF = 5;
  /** RegularExpression Id. */
  int ELSE = 6;
  /** RegularExpression Id. */
  int VOID = 7;
  /** RegularExpression Id. */
  int INT = 8;
  /** RegularExpression Id. */
  int CHAR = 9;
  /** RegularExpression Id. */
  int BOOL = 10;
  /** RegularExpression Id. */
  int STRING = 11;
  /** RegularExpression Id. */
  int CONST = 12;
  /** RegularExpression Id. */
  int NATIVE = 13;
  /** RegularExpression Id. */
  int NUMBERIC_LITERAL = 14;
  /** RegularExpression Id. */
  int STRING_LITERAL = 15;
  /** RegularExpression Id. */
  int IDENTIFIER = 16;
  /** RegularExpression Id. */
  int IDENTIFIER_START = 17;
  /** RegularExpression Id. */
  int IDENTIFIER_PART = 18;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\r\"",
    "\"\\n\"",
    "\"if\"",
    "\"else\"",
    "\"void\"",
    "\"int\"",
    "\"char\"",
    "\"bool\"",
    "\"string\"",
    "\"const\"",
    "\"native\"",
    "<NUMBERIC_LITERAL>",
    "<STRING_LITERAL>",
    "<IDENTIFIER>",
    "<IDENTIFIER_START>",
    "<IDENTIFIER_PART>",
    "\"{\"",
    "\"}\"",
    "\";\"",
  };

}
