/* Generated By:JavaCC: Do not edit this line. GALParserConstants.java */
package org.zhjh.galaxykit.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface GALParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int IF = 6;
  /** RegularExpression Id. */
  int ELSE = 7;
  /** RegularExpression Id. */
  int WHILE = 8;
  /** RegularExpression Id. */
  int BREAK = 9;
  /** RegularExpression Id. */
  int CONTINUE = 10;
  /** RegularExpression Id. */
  int VOID = 11;
  /** RegularExpression Id. */
  int BOOL = 12;
  /** RegularExpression Id. */
  int INT = 13;
  /** RegularExpression Id. */
  int FIXED = 14;
  /** RegularExpression Id. */
  int STRING = 15;
  /** RegularExpression Id. */
  int STRUCT = 16;
  /** RegularExpression Id. */
  int CONST = 17;
  /** RegularExpression Id. */
  int NATIVE = 18;
  /** RegularExpression Id. */
  int INCLUDE = 19;
  /** RegularExpression Id. */
  int RETURN = 20;
  /** RegularExpression Id. */
  int TRUE = 21;
  /** RegularExpression Id. */
  int FALSE = 22;
  /** RegularExpression Id. */
  int NULL = 23;
  /** RegularExpression Id. */
  int DIV = 24;
  /** RegularExpression Id. */
  int INTEGER_LITERAL = 25;
  /** RegularExpression Id. */
  int DECIMAL_INTEGER = 26;
  /** RegularExpression Id. */
  int FLOAT_LITERAL = 27;
  /** RegularExpression Id. */
  int STRING_LITERAL = 28;
  /** RegularExpression Id. */
  int IDENTIFIER = 29;
  /** RegularExpression Id. */
  int IDENTIFIER_START = 30;
  /** RegularExpression Id. */
  int IDENTIFIER_PART = 31;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\r\"",
    "\"\\n\"",
    "<token of kind 5>",
    "\"if\"",
    "\"else\"",
    "\"while\"",
    "\"break\"",
    "\"continue\"",
    "\"void\"",
    "\"bool\"",
    "\"int\"",
    "\"fixed\"",
    "\"string\"",
    "\"struct\"",
    "\"const\"",
    "\"native\"",
    "\"include\"",
    "\"return\"",
    "\"true\"",
    "\"false\"",
    "\"null\"",
    "\"/\"",
    "<INTEGER_LITERAL>",
    "<DECIMAL_INTEGER>",
    "<FLOAT_LITERAL>",
    "<STRING_LITERAL>",
    "<IDENTIFIER>",
    "<IDENTIFIER_START>",
    "<IDENTIFIER_PART>",
    "\"=\"",
    "\";\"",
    "\"{\"",
    "\"}\"",
    "\",\"",
    "\"(\"",
    "\")\"",
    "\"+=\"",
    "\"-=\"",
    "\"*=\"",
    "\"/=\"",
    "\"%=\"",
    "\"&=\"",
    "\"^=\"",
    "\"|=\"",
    "\"&\"",
    "\"*\"",
    "\"!\"",
    "\"~\"",
    "\".\"",
    "\"->\"",
    "\"%\"",
    "\"+\"",
    "\"-\"",
    "\">\"",
    "\"<\"",
    "\">=\"",
    "\"<=\"",
    "\"==\"",
    "\"!=\"",
    "\"^\"",
    "\"|\"",
    "\"&&\"",
    "\"||\"",
    "\"[\"",
    "\"]\"",
  };

}
